---
title: "Cluster notes 10/6/25"
format: html
editor: visual
---

## Cluster notes 10/6/25

How to connect to cluster:

(if not computing)

open putty -\>

type cbsulogin.biohpc.cornell.edu into host,

use ssh, port 22

(saved as clusterloginserver)

login with netID and cluster password

pwd=printworkingdirectory

mkdir=makedirectory

To transfer files to cluster from computer

then- connect to filezilla, same login as putty, putting sftp:// beforeahnd, port 22

cbsulogin.biohpc.cornell.edu

one thing as a pc user is to make sure your scripts have line endings as unix line endings, which could cause problems

ls -l lists everything in a dir with sizes

top lets you see everything running

q lets you out of top

theres some nuance between how I got data frmo unh and how I got back from biohpc, so theres some naming conventions that TASOS will know, ask them for scripts!

how to get to a working directory

-ask bronwyn

Things bronwyn says to know-

is accessing from not campus, you can access the login server, but not a working machine

if not behind the firewall, gottarun cisco cornell vpn

if running studd on cluster but it disconnects, itll sometimes send a hangup signal and STOP whatever you are running, need to learn how to stop that from happening by asking bronwyn

exit/close from terminal disconnects but dont end reservation

the cluster is not deep storage, but the BRC does have deep storage
